spring:
#  profiles: dev
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://ep-wispy-scene-a1ajzwow.ap-southeast-1.aws.neon.tech:5432/postgres
    username: mh.lee239
    password: hSaDcMFC05sm
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        default_schema: db